### PR TITLE
fix: remove vendoring from this repo

### PR DESCRIPTION
**Pull request by jdtuhui**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
 Remove vendor folder,   Use go.mod to download dependent code
#### Which issue(s) this PR fixes:

Fixes #
https://github.com/kubernetes-sigs/scheduler-plugins/issues/760
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by jaypipes** [comment]
@Huang-Wei @zwpaper thoughts on this PR? :)

**Comment by googs1025** [comment]
@jdtuhui we should fix `EasyCLA` first.
Also, I think this is not a kind bug classification, but a cleanup classification, please let me know if I am wrong.

**Comment by Huang-Wei** [comment]
We used to add `vendor/` intentionally b/c of some code (zz_openapi*.go) are excluded in git, but needed to make codegen functional. So it ends up developer having to locally install necessary toolkit to do codegen, which is quite cumbersome.

But due to recent refactoring on codegen scripts (both this repo and upstream), those zz_openapi*.go might not be needed, and hence we can get rid of the whole vendor/ folder.

cc @zwpaper @denkensk @ffromani

**Comment by ffromani** [comment]
> We used to add `vendor/` intentionally b/c of some code (zz_openapi*.go) are excluded in git, but needed to make codegen functional. So it ends up developer having to locally install necessary toolkit to do codegen, which is quite cumbersome.
> 
> But due to recent refactoring on codegen scripts (both this repo and upstream), those zz_openapi*.go might not be needed, and hence we can get rid of the whole vendor/ folder.
> 
> cc @zwpaper @denkensk @ffromani

I for myself I don't have strong opinions on the matter.  If there is user demand to remove `vendor/` and we have options projectwise to do so, then why not?

**Comment by zwpaper** [comment]
I would prefer dropping the `vendor/` dir if we do not need it for codegen anymore, that would reduce unnecessary changes for PRs, and we can focus more on our core logic.

**Pull request closed without merging**
