### PR TITLE
add subtitle for trimaran in plugin list

### PR DESCRIPTION
**Pull request by haorenfsa**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:

Make it easier for new users to find out there's a load-aware scheduling plugin available already.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
@atantawi does it look good?

**Comment by atantawi** [comment]
> @atantawi does it look good?

/lgtm

**Pull request merged**
