### PR TITLE
Update Compatibility Matrix For v0.19.9 Release

### PR DESCRIPTION
**Pull request by seanmalloy**

### CODE REVIEW

**Comment by seanmalloy** [comment]
Let wait until https://github.com/kubernetes/k8s.io/pull/1879 is merged.

/kind documentation
/hold

**Comment by seanmalloy** [comment]
I can cherry-pick this back to the release-1.19 branch if we want.

/hold cancel
/assign @Huang-Wei 
/cc @denkensk

**Comment by Huang-Wei** [comment]
/lgtm
/approve

> I can cherry-pick this back to the release-1.19 branch if we want.

I think it's fine to not cherry-pick the docs

**Comment by seanmalloy** [comment]
I verified the images can be pulled from the official k8s registry.
```
docker pull k8s.gcr.io/scheduler-plugins/kube-scheduler:v0.19.9
docker pull k8s.gcr.io/scheduler-plugins/controller:v0.19.9
```

**Pull request merged**
