### PR TITLE
bump k8s deps to v1.27.10

### PR DESCRIPTION
**Pull request by zwpaper**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
1. bump k8s deps to v1.27.10
2. add helm chart ci

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

please add a tag and release for the v1.27.10, 
so that CI could create a helm chart and we could host it on Netlify page
@Huang-Wei 

#### Does this PR introduce a user-facing change?

```release-note
bump k8s deps to v1.27.10
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
@zwpaper this PR needs a rebase (I guess due to another PR merged)

**Comment by zwpaper** [comment]
looks like there may be some problems with the ci bot? the merged commits are right in this PR but leaving the PR open and conflict.

should we close the PR directly or look into the CI issue? @Huang-Wei

**Comment by zwpaper** [comment]
@Huang-Wei Maybe we can close this directly, and release the v1.27.10? 
as the commits are actually merged

**Comment by Huang-Wei** [comment]
> What this PR does / why we need it:
- bump k8s deps to v1.27.10
- add helm chart ci

The k8s deps bump portion has been merged, but not the helm chart part. Do you want to check in that part only?

**Comment by zwpaper** [comment]
CleanShot 2024-02-06 at 16 28 41

it seems that all the 3 commits are merged, even a PR merge commit is created

**Comment by zwpaper** [comment]
@Huang-Wei could you please create a release for the v1.27.10?

**Pull request closed without merging**
