### PR TITLE
refactor: replace math.Min/math.Max with min/max

### PR DESCRIPTION
**Pull request by alexandear**
#### What type of PR is this?

The PR refactors code by replacing `math.Min/math.Max` with builtin `min/max`.

/kind cleanup

#### What this PR does / why we need it:

It simplifies code.

#### Special notes for your reviewer:

https://pkg.go.dev/builtin@go1.22.0#min
https://pkg.go.dev/builtin@go1.22.0#max

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by Huang-Wei — COMMENTED** [review]
Thanks @alexandear .

Would you mind fixing all the hand-crafted min/max in this repo?

```
⇒  ag math.Min
pkg/networkaware/networkoverhead/networkoverhead.go
423:	var max int64 = math.MinInt64 // Set to min value

pkg/trimaran/lowriskovercommitment/lowriskovercommitment.go
223:		sigma = math.Min(sigma, math.Sqrt(GetMaxVariance(mu)*MaxVarianceAllowance))
227:		allocThreshold = math.Min(math.Max(allocThreshold, 0), 1)
241:					allocProb = math.Min(math.Max(allocProb, 0), 1)
255:	totalRisk = math.Min(math.Max(totalRisk, 0), 1)

pkg/trimaran/loadvariationriskbalancing/analysis.go
42:	rs.UsedAvg = math.Max(math.Min(rs.UsedAvg, rs.Capacity), 0)
43:	rs.UsedStdev = math.Max(math.Min(rs.UsedStdev, rs.Capacity), 0)
54:	sigma = math.Max(math.Min(sigma, 1), 0)

pkg/trimaran/loadvariationriskbalancing/loadvariationriskbalancing.go
116:		totalScore = math.Min(memoryScore, cpuScore)

pkg/trimaran/resourcestats_test.go
525:					MilliCPU: int64(math.Min(float64(GetResourceRequested(pod).MilliCPU), float64(capCpu))),
526:					Memory:   int64(math.Min(float64(GetResourceRequested(pod).Memory), float64(capMem))),
558:					MilliCPU: int64(math.Min(float64(GetResourceRequested(pod4).MilliCPU), float64(capCpu))),
559:					Memory:   int64(math.Min(float64(GetResourceRequested(pod4).Memory), float64(capMem))),
562:					MilliCPU: int64(math.Min(
565:					Memory: int64(math.Min(

pkg/trimaran/resourcestats.go
83:	mu = math.Max(math.Min(mu, 1), 0)
85:	sigma = math.Max(math.Min(sigma, 1), 0)
```

**Comment by alexandear** [comment]
> Would you mind fixing all the hand-crafted min/max in this repo?

Done.

**Review by Huang-Wei — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
