### PR TITLE
Allow specifying the scheduler container entrypoint in the helm chart

### PR DESCRIPTION
**Pull request by chotiwat**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

The current chart template doesn't support the older kube-scheduler image which doesn't specify ENTRYPOINT in the image. This PR allows customizing the container entrypoint through the new `scheduler.command` value.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
By "older kube-scheduler image", do you mean the v0.29.7 image? If so, we changed back the default entrypoint to /bin/scheduler (#794) - which is available in v0.29.8 and master.

And we will keep the path unchanged in the future, for backwards compatibility. Did it resolve your issue?

xref: https://kubernetes.slack.com/archives/C09TP78DV/p1723546975114219

**Comment by chotiwat** [comment]
@Huang-Wei By older images, I mean the ones before v0.29, e.g. https://github.com/kubernetes-sigs/scheduler-plugins/blob/v0.27.9/build/scheduler/Dockerfile#L28. I'd like to use the latest chart with an older image version to match my org's k8s clusters.

**Comment by Huang-Wei** [comment]
ok, I see the motiviation.

/ok-to-test

**Pull request merged**
