### PR TITLE
Move doc/release-guide.md to RELEASE.md

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind documentation
/kind cleanup

#### What this PR does / why we need it:

Move doc/release-guide.md to RELEASE.md.
RELEASE.md doesn't seem to be used.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

Please let me know if this RELEASE.md is still needed/used. I just want to know what is exactly needed for release to create a similar doc in [sigs/kube-scheduler-simulator](https://github.com/kubernetes-sigs/kube-scheduler-simulator).

### CODE REVIEW

**Comment by denkensk** [comment]
It was because we bumped go version to 1.17 in master today https://github.com/kubernetes/test-infra/pull/25196
You can change like this in hack/tools.go
```bash
diff --git a/hack/tools.go b/hack/tools.go
index e661963..dfc4592 100644
--- a/hack/tools.go
+++ b/hack/tools.go
@@ -1,3 +1,4 @@
+//go:build tools
 // +build tools

 /*
```

**Comment by sanposhiho** [comment]
I raised the change as another PR.
https://github.com/kubernetes-sigs/scheduler-plugins/pull/336

**Comment by sanposhiho** [comment]
I'll rebase this PR after #336 gets merged.

**Comment by sanposhiho** [comment]
rebased.

**Comment by Huang-Wei** [comment]
@sanposhiho instead of deleting it, could you merge doc/release-guide here?

**Comment by sanposhiho** [comment]
@Huang-Wei Fixed.

**Pull request merged**
