### PR TITLE
Fix list items numbering

### PR DESCRIPTION
**Pull request by Fish-pro**
Signed-off-by: Fish-pro <zechun.chen@daocloud.io>

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

When reading the document through the code, it turns out that the order list in the document is wrong, and this pr fixes the problem

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by PiotrProkop** [comment]
@Fish-pro the syntax is correct Markdown allows to use only `1.` in ordered lists and it will be automatically converted into proper indexes, check reference here:
https://www.markdownguide.org/basic-syntax/#ordered-lists

**Comment by Fish-pro** [comment]
> @Fish-pro the syntax is correct Markdown allows to use only `1.` in ordered lists and it will be automatically converted into proper indexes, check reference here: https://www.markdownguide.org/basic-syntax/#ordered-lists

Thanka for tips，I understand that either way is OK, whether it would be better to follow the order？

**Comment by PiotrProkop** [comment]
> > @Fish-pro the syntax is correct Markdown allows to use only `1.` in ordered lists and it will be automatically converted into proper indexes, check reference here: https://www.markdownguide.org/basic-syntax/#ordered-lists
> 
> Thanka for tips，I understand that either way is OK, whether it would be better to follow the order？

I think it brings unnecessary burden 😄 for me using `1` everywhere is simpler and consistent. But this is my opinion.

**Comment by Fish-pro** [comment]
> > > @Fish-pro the syntax is correct Markdown allows to use only `1.` in ordered lists and it will be automatically converted into proper indexes, check reference here: https://www.markdownguide.org/basic-syntax/#ordered-lists
> > 
> > 
> > Thanka for tips，I understand that either way is OK, whether it would be better to follow the order？
> 
> I think it brings unnecessary burden 😄 for me using `1` everywhere is simpler and consistent. But this is my opinion.

@PiotrProkop Thanks, I will close this pr

**Comment by Fish-pro** [comment]
> > > @Fish-pro the syntax is correct Markdown allows to use only `1.` in ordered lists and it will be automatically converted into proper indexes, check reference here: https://www.markdownguide.org/basic-syntax/#ordered-lists
> > 
> > 
> > Thanka for tips，I understand that either way is OK, whether it would be better to follow the order？
> 
> I think it brings unnecessary burden 😄 for me using `1` everywhere is simpler and consistent. But this is my opinion.

@PiotrProkop Thanks, I will close this pr

**Comment by Huang-Wei** [comment]
I'm with @PiotrProkop on using constant `1` for bullet listing :)

**Pull request closed without merging**
