### PR TITLE
fix typo mistake

### PR DESCRIPTION
**Pull request by maoyangLiu**
/kind documentation
fix typo mistake in readme

### CODE REVIEW

**Review by swatisehgal — APPROVED** [review]
/lgtm

Thanks for the PR. I think in the long run it is worth adding a CI lane to perform a spellcheck before the PR gets merged. I will invest some time into this when I have some bandwidth.

**Comment by swatisehgal** [comment]
/assign @ffromani @Huang-Wei 
for approval

**Comment by ffromani** [comment]
/approve

thanks!

**Pull request merged**
