### PR TITLE
Move manual codegen bits out of zz_generated*.go

### PR DESCRIPTION
**Pull request by Huang-Wei**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR separates manual codegen bits out of zz_generated*.go, to a standalone `conversion.go`, so that zz_generated*.go are purely auto-generated without any manual bits. This can help maintain the codebase easily.

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Review by wangchen615 — APPROVED** [review]
/LGTM

**Comment by fromanirh** [comment]
/lgtm
cool, this looks like a generalization of my https://github.com/kubernetes-sigs/scheduler-plugins/pull/427!

**Pull request merged**
