### PR TITLE
Bump kubernetes deps to 0.26.7

### LINKED ISSUE #597: Supports for K8s 1.26.0
### Area

- [X] Scheduler
- [X] Controller
- [X] Helm Chart
- [X] Documents

### Other components

_No response_

### What happened?

Wait for the scheduler 0.26

### What did you expect to happen?

Hello, how long will K8s 1.26.6 be supported?
I've been using 1.26 for a while and have been waiting for this release.
Thanks for your reply!

### How can we reproduce it (as minimally and precisely as possible)?

0

### Anything else we need to know?

0

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"11902a838028edef305dfe2f96be929bc4d114d8", GitTreeState:"clean", BuildDate:"2023-06-14T09:56:58Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"11902a838028edef305dfe2f96be929bc4d114d8", GitTreeState:"clean", BuildDate:"2023-06-14T09:49:08Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Scheduler Plugins version

<details>
0.26
</details>

### PR DESCRIPTION
**Pull request by PiotrProkop**
#### What type of PR is this?

Bump Kubernetes deps to 0.26.7 for 0.26 release.

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #597

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by PiotrProkop** [comment]
@Huang-Wei PTAL, wanted to help with the `0.26` release.

**Comment by Huang-Wei** [comment]
Thanks @PiotrProkop .

/approve

**Pull request merged**
