### PR TITLE
coscheduling: PostFilter handles both Filter and PreFilter

### PR DESCRIPTION
**Pull request by mateuszlitwin**
Currently, coscheduling.PostFilter rejects waiting pods only if coscheduling.PreFilter did not fail.

I think pod group pods should be rejected regardless. For example, if `minResources` check failed in PreFilter we should reject waiting pods in PostFilter.

Thread on slack: https://kubernetes.slack.com/archives/C09TP78DV/p1638478990123200

CC @denkensk @cwdsuzhou @Huang-Wei

### CODE REVIEW

**Review by Huang-Wei — COMMENTED** [review]
Given the logic of proactively activate a group of pods is in place, I'm fine with this aggressive strategy to reject a group of pods when default preemption doesn't help.

/approve
/hold

Leaving /lgtm to @denkensk and @cwdsuzhou .

**Comment by mateuszlitwin** [comment]
Yeah, with pod activation being in place I think we can be more aggressive with pod group rejections. I also think it will make plugin easier to understand and more predictable.

**Comment by denkensk** [comment]
/lgtm
/unhold
Thanks @mateuszlitwin

**Pull request merged**
