### PR TITLE
cleanup: remove vendoring

### LINKED ISSUE #760: request: remove vendoring from this repo
### Area

- [X] Scheduler
- [X] Controller
- [ ] Helm Chart
- [ ] Documents

### Other components

_No response_

### What happened?

We mirror the scheduler-plugins repository into our private build servers in order to comply with our secure software supply chain policies. There is governance and vulnerability automation that scans the repository for CVEs and licensing issues. Unfortunately, this repository uses Go vendoring which means two things:

1. When we pull in new upstream code, we need to pull in sometimes millions of lines of code (most of which is in the `vendor/` folder) making it difficult if not impossible to know what outside of the dependencies has changed.
2. Our governance and CVE automation scans all the vendored code and alerts on everything it finds, and we need to manually change the go.mod file to include "fixed" versions of dependencies (many times there isn't, frankly, a usable version of a dependency because of incompatible 0-series versions, but we still have to struggle through trying to update the dependency anyway)

If this repo didn't use vendoring, our life would be a whole lot easier because a) there'd be a whole lot less code in the repository and Git commits and b) we could take advantage of modern Go module tooling that essentially obviates the need for vendoring entirely.

In the topologyawarewg and networkplumbingwg I've already merged PRs that remove vendoring from a bunch of their repos and that's helped tremendously in simplifying life for those of us who have to build components using internal build tooling. Would it be possible to remove vendoring from the scheduler-plugins repo?

### What did you expect to happen?

n/a

### How can we reproduce it (as minimally and precisely as possible)?

_No response_

### Anything else we need to know?

_No response_

### Kubernetes version

all

### Scheduler Plugins version

all

### PR DESCRIPTION
**Pull request by binacs**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #760 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by binacs** [comment]
cc @Huang-Wei 

PTAL, thanks!

**Review by Huang-Wei — COMMENTED** [review]
Thank you so much, @binacs!

Could you please help with the following?

1. Split the PR into two commits:
- One commit for the code changes only
- Another commit for the removal of the `vendor/` directory
2. Update `hack/update-codegen.sh`:
- Ensure the script runs successfully and generates no differences in the current codebase
- Test it by making some mock changes (e.g., removing some API fields) and verify that it produces the expected output

**Comment by binacs** [comment]
hi @Huang-Wei , thanks for review!

I have split all changes into two commits as required. Modified the `verify/crdgen.sh` and ensure that the codebase does not change. I have done relevant tests locally and it seems to be ok.

**Comment by Huang-Wei** [comment]
> Modified the hack/verify-crdgen.sh and ensure that the codebase does not change.

I meant `hack/update-codegen.sh`, not `hack/verify-crdgen.sh`.

**Comment by binacs** [comment]
hi @Huang-Wei , I pushed a commit to modify `hack/update-codegen.sh` and it seems to work fine (no diffs are generated).

```
@binacs ➜ /workspaces/scheduler-plugins (binacs/remove-vendoring) $ ./hack/update-codegen.sh 
Generating deepcopy code for 2 targets
Generating defaulter code for 1 targets
Generating conversion code for 1 targets
Generating applyconfig code for 1 targets
Generating client code for 1 targets
Generating lister code for 1 targets
Generating informer code for 1 targets
```

BTW, I modified the `hack/verify-crdgen.sh` before to make sure that we will only generate NodeResourceTopology#v1alpha2 apis (according to https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/manifests/noderesourcetopology/crd.yaml).

> master's vendor[**Only v1alpha2**]: https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/vendor/github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis/topology
> 
> upstream repo [**Both v1alpha1 and v1alpha2**]: https://github.com/k8stopologyawareschedwg/noderesourcetopology-api/tree/master/pkg/apis/topology)

```diff
# Only represent the github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis
- api_paths="XXX;./vendor/github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis/...;XXX"
+ api_paths="XXX;github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis/topology/v1alpha2;XXX"
```



Please take a look, thanks!

**Review by Huang-Wei — COMMENTED** [review]
/lgtm
/approve

Thanks again!

**Pull request merged**
