### PR TITLE
Bump 1.20

### PR DESCRIPTION
**Pull request by Huang-Wei**
Bump the k/k dependency to 1.20.

### CODE REVIEW

**Comment by Huang-Wei** [comment]
/assign @seanmalloy 

This is ready for review.

**Comment by seanmalloy** [comment]
I have reviewed to the best of my ability. @Huang-Wei I'm adding a hold just in case you want an additional person to review before merge. Feel free to remove the hold if you'd like this merged.

/lgtm
/hold

**Pull request merged**
