### PR TITLE
[noderesourcetopology] improve classification of resources

### PR DESCRIPTION
**Pull request by ffromani**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Improves over #646 with unification and consolidation of resource classification with respect to expected NUMA affinity

Fixes # N/A

#### Special notes for your reviewer:
N/A

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by PiotrProkop** [comment]
/lgtm 
should make code more readable. Thanks!

**Comment by ffromani** [comment]
> /lgtm should make code more readable. Thanks!

Indeed. But more than that, I think we need this cleanup to have a clear picture of what resources should provide numa-affinity and what not. In addition, I think even after #646 we could have the same bug for `storage` (but I didn't check).
Thanks for the quick review!

**Pull request merged**
