### PR TITLE
nodetopologymatch: bump deps

### PR DESCRIPTION
**Pull request by ffromani**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Bump dependencies used by the nodetopologymatch plugin, catching up with simplifications provided by upstream libraries

#### Which issue(s) this PR fixes:
Fixes #N/A

#### Special notes for your reviewer:
Gather minor cleanups we discussed during past reviews. No expected impact in behavior

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by PiotrProkop** [comment]
LGTM 🚀 
I can properly approve this PR when `WIP` is removed from it's title.
Any plans to add something more to this PR?

**Comment by ffromani** [comment]
> LGTM rocket I can properly approve this PR when `WIP` is removed from it's title. Any plans to add something more to this PR?

I want to do another pass later to cleanup. I don't plan to add much more though.

We are starting to work towards improving the observability of the plugin, but there's nothing ready yet and no ETA either.

**Comment by ffromani** [comment]
/hold

for the final verification (that's on me)

**Comment by ffromani** [comment]
/hold cancel

did my own extra verification, looks good

**Pull request merged**
