### PR TITLE
Bump master to 1.19

### PR DESCRIPTION
**Pull request by Huang-Wei**
- update go module
    - [x] go version to 1.15
    - [x] klog to v2
    - [x] k8s deps to v1.19.0
- versioned `CoschedulingArgs`
    - [x] ensure config API's GVK aligned with in-tree ComponentConfig API
    - [x] API, codegen and CI scripts
- core logic adapted to new interfaces of scheduler in 1.19
    - [x] adapting logic to new SharedSnapshotLister interface
- verify tests work
    - [x] UT and Integration test works with the trick of enforcing initialization of `scheme` pkg
    - [x] manually test `CoschedulingArgs` to ensure it works in an end-to-end workflow (nil args gets defaulted, and non-default args are horned properly)

### CODE REVIEW

**Comment by Huang-Wei** [comment]
/cc @yuanchen8911 @denkensk This PR is ready fo review.

FYI: @cwdsuzhou

**Comment by Huang-Wei** [comment]
I tried to categorize the changeset into commits. It should be inconvinient to review the code by commits.

**Comment by yuanchen8911** [comment]
> /cc @yuanchen8911 @denkensk This PR is ready fo review.
> 
> FYI: @cwdsuzhou

Will look.

**Comment by denkensk** [comment]
/lgtm 
Thank you for your great work.

**Pull request merged**
