### PR TITLE
site: add chart index to site

### PR DESCRIPTION
**Pull request by zwpaper**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

add chart index to site so that we can use the site as chart repo,
and pull chart from our github releases

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes-sigs/scheduler-plugins/issues/620

#### Does this PR introduce a user-facing change?

```release-note
Helm charts are now hosted on https://scheduler-plugins.sigs.k8s.io. You can install a scheduler-plugin chart via `helm install --repo https://scheduler-plugins.sigs.k8s.io scheduler-plugins scheduler-plugins`
```

### CODE REVIEW

**Comment by zwpaper** [comment]
after this one merge, we can use the site as chart repo like:

the URL should be https://scheduler-plugins.sigs.k8s.io/ after merged to master

```console
kweizh@weim /tmp [1]> helm repo add pr https://deploy-preview-737--kubernetes-sigs-scheduler-plugins.netlify.app
"pr" has been added to your repositories
kweizh@weim /tmp> helm repo update pr
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "pr" chart repository
Update Complete. ⎈Happy Helming!⎈
kweizh@weim /tmp> helm search repo pr
NAME                	CHART VERSION	APP VERSION	DESCRIPTION
pr/scheduler-plugins	0.28.8       	0.28.8     	deploy scheduler plugin as a second scheduler i...
```

**Comment by Huang-Wei** [comment]
It's fabulous @zwpaper ! Cannot wait to see its publish.

Could you reword the release notes a bit? something like:

```
Helm charts are now hosted on https://scheduler-plugins.sigs.k8s.io/. You can install a scheduler-plugin chart via ...
```

**Review by Huang-Wei — COMMENTED** [review]
/approve

**Comment by zwpaper** [comment]
release note updated, PTAL @Huang-Wei

**Pull request merged**
