### PR TITLE
Update rbac.yaml to avoid "Failed to watch" error

### PR DESCRIPTION
**Pull request by wangchen615**
This is to resolve and close issue #271 .

### CODE REVIEW

**Comment by denkensk** [comment]
/lgtm
Thanks @wangchen615

**Comment by Huang-Wei** [comment]
@wangchen615 the root cause is the RBAC rules applied to the secondary scheduler doesn't fully "copy" the ones applied to default scheduler, in particular, access to configmap "extension-apiserver-authentication". This was fixed in the upstream by creating a RoleBinding: https://github.com/kubernetes/kubernetes/pull/72491

So I think we should follow the same way here, instead of imposing a direct configmap access. 

I raised PR #272 earlier, could you verify if it works?

**Comment by wangchen615** [comment]
Ok, I will close this PR then.
> same way here, instead of imposing a direct con



> #272

**Pull request closed without merging**
