### PR TITLE
docs: add args struct convention name

### PR DESCRIPTION
**Pull request by juliorenner**
Just adds to the documentation what Huang-Wei explained me in slack channel:

https://kubernetes.slack.com/archives/C09TP78DV/p1618378191077700

### CODE REVIEW

**Comment by juliorenner** [comment]
Just signed the CLA.

**Comment by seanmalloy** [comment]
Looks like this would resolve #186.

/ok-to-test
/cc @lianghao208 @denkensk 
/kind documentation

**Comment by Huang-Wei** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
