### PR TITLE
Code changes for PEAKS plugin 

### LINKED ISSUE #800: K8s plugin for Power Efficiency Aware Kubernetes Scheduling (PEAKS)
### Area

- [X] Scheduler
- [ ] Controller
- [ ] Helm Chart
- [ ] Documents

### Other components

_No response_

### What happened?

The energy efficiency of different nodes of a Kubernetes cluster is not the same typically. However, current Kubernetes scheduler doesn't have any capability to distinguish the difference in the energy efficiency of different nodes to prioritize selection of the nodes with higher energy efficiency over nodes with lower energy efficiency for the pod placement. 

### What did you expect to happen?

Create a Kubernetes Enhancement Proposal (KEP) motivating the need for a scheduler plugin (to achieve energy efficiency aware scheduling of pods on nodes) and also capture the functional details of one such plugin. Subsequently implement the proposed energy efficiency aware K8s scheduler plugin.

### How can we reproduce it (as minimally and precisely as possible)?

_No response_

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Scheduler Plugins version

<details>

</details>

### PR DESCRIPTION
**Pull request by fali007**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Code changes for the scheduler plugin for energy efficiency aware scheduling of pods on nodes (prioritize nodes with higher energy efficiency over nodes with lower energy efficiency for pod placement)
#### Which issue(s) this PR fixes:

Fixes #
Fixes #800 
#### Special notes for your reviewer:
NONE
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by knarayan** [comment]
This is the same PR as https://github.com/kubernetes-sigs/scheduler-plugins/pull/829 (fixing some branch issues in that PR)

**Review by Huang-Wei — COMMENTED** [review]
/lgtm
/approve

**Comment by knarayan** [comment]
Whoever is interested in this PR, we request that you refer to the related PRs #810 and #829 for the code review comments. There were a lot of code review comments provided by the reviewers, and we have addressed all of them.

Thanks a lot, @Huang-Wei and @PiotrProkop, for reviewing our code and ensuring that our code changes meet the required quality standards for merging.

**Pull request merged**
