### PR TITLE
allow priorityClassName to be configured in Helm chart

### PR DESCRIPTION
**Pull request by shkrid**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

adds the ability for defining priorityClassName

#### Does this PR introduce a user-facing change?
```release-notes
Added the ability in Helm chart for defining priorityClassName
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
@shkrid thanks for the PR. Could you add a short stanza in the `release-notes` section in the PR body?

**Comment by shkrid** [comment]
@Huang-Wei Fixed. Is that good enough?

**Review by Huang-Wei — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
