### PR TITLE
bump k8s dependencies to v1.30.4

### PR DESCRIPTION
**Pull request by Huang-Wei**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

bump k8s dependencies to v1.30.4

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
https://github.com/kubernetes/test-infra/pull/33337 to update Go version for CI jobs.

**Comment by Huang-Wei** [comment]
cc @ffromani @denkensk @zwpaper

**Comment by ffromani** [comment]
/lgtm

seems a trivial bump

**Comment by ffromani** [comment]
/hold

to let other reviewers chime in

**Comment by Tal-or** [comment]
/lgtm
+1

**Pull request merged**
