### PR TITLE
deps: upgrade 1.25 deps to 0.25.12

### PR DESCRIPTION
**Pull request by zwpaper**
#### What this PR does / why we need it:

upgrade 1.25 release dependencies to 1.25.12

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes-sigs/scheduler-plugins/issues/629

#### Does this PR introduce a user-facing change?

```release-note
upgrade target kubernetes dependencies to v0.25.12
```

### CODE REVIEW

**Comment by zwpaper** [comment]
Should I update the docs in the same PR or wait for the image to be built and create a new one?

**Comment by Huang-Wei** [comment]
> 
Should I update the docs in the same PR or wait for the image to be built and create a new one?

You can do that after the image is out.

**Pull request merged**
