### PR TITLE
docs: update the version of scheduler config and use MultiPoint to simplify them

### LINKED ISSUE #673: doc: manifest updates to use v1 as scheduler config and multipoint
I'd propose the following doc/manifest update:

- [ ] use v1 (instead of v1beta3) as the version of all scheduler config yamls
- [ ] use `MultiPoint` to simplify configuring each plugin

/kind doc
/good-first-issue

### PR DESCRIPTION
**Pull request by lianghao208**
#### What type of PR is this?
/kind cleanup
/kind documentation

#### What this PR does / why we need it:
Since #670 has been merged, we need to update scheduler config version from v1beta3 to v1
#### Which issue(s) this PR fixes:

Fixes #673

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
@lianghao208 we may on-hold this due to recently found bug in upstream https://github.com/kubernetes/kubernetes/issues/122066

**Comment by lianghao208** [comment]
> @lianghao208 we may on-hold this due to recently found bug in upstream [kubernetes/kubernetes#122066](https://github.com/kubernetes/kubernetes/issues/122066)

@Huang-Wei friendly ping, the upstream bug has been merged

**Comment by panpan0000** [comment]
Hi, @lianghao208 
maybe you can also address  a few files in docs ?
image

PS: I've closed my PR https://github.com/kubernetes-sigs/scheduler-plugins/pull/688/files

**Comment by lianghao208** [comment]
> Hi, @lianghao208 maybe you can also address a few files in docs ? image
> 
> PS: I've closed my PR https://github.com/kubernetes-sigs/scheduler-plugins/pull/688/files

@panpan0000 Thanks for reminding me, I've updated these files.

**Comment by Huang-Wei** [comment]
Let's merge it for now, and we will bump the version before releasing to pick up the changes of https://github.com/kubernetes/kubernetes/issues/122066

/lgtm
/approve

**Pull request merged**
