### PR TITLE
bump k8s deps to 1.27

### LINKED ISSUE #606: controller-runtime version 0.14.X incompatible with client-go 0.27
Usually the first step after releasing is to bump the k8s deps in master branch. But in local testing, it turns out a change in client-go caused all controller-runtime 0.14.X versions incompatible.

- issue https://github.com/operator-framework/operator-sdk/issues/6396 has been reported elsewhere
- to be compatible with k8s v1.27, we need to vendor a controller-runtime version (v0.15.0+) that contains the fix: https://github.com/kubernetes-sigs/controller-runtime/pull/2223

### PR DESCRIPTION
**Pull request by Huang-Wei**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

- bump go version to 1.20
- bump k8s version to 1.27
- bump controller-runtime to 0.15

#### Which issue(s) this PR fixes:

Fixes #606

#### Does this PR introduce a user-facing change?

```release-note
Bump go version to 1.20 and k8s deps to 1.27
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
@zwpaper you can take over if you have bandwidth.

Atop this PR, UT in `pkg/controllers/elasticquota_controller_test.go` failed. I haven't have cycle to look into it yet.

**Comment by zwpaper** [comment]
added a PR here https://github.com/Huang-Wei/scheduler-plugins/pull/1 to fix the failing test.

will do a full test later @Huang-Wei

**Comment by Huang-Wei** [comment]
> added a PR here [Huang-Wei#1](https://github.com/Huang-Wei/scheduler-plugins/pull/1) to fix the failing test.

Thanks a lot! I've merged that one in the fork repo, and push here.

I'm going to tweak the CI to use go 1.20, and then have the CI start here.

**Comment by Huang-Wei** [comment]
CI failure:

```
--- FAIL: TestCapacityScheduling (34.38s)
    capacity_scheduling_test.go:59: The CRD is ready to serve
    capacity_scheduling_test.go:87: Init scheduler success
    --- FAIL: TestCapacityScheduling/cross-namespace_preemption (10.32s)
        capacity_scheduling_test.go:553: cross-namespace preemption Waiting expectedPods error: timed out waiting for the condition
    --- FAIL: TestCapacityScheduling/in-namespace_preemption (10.32s)
        capacity_scheduling_test.go:553: in-namespace preemption Waiting expectedPods error: timed out waiting for the condition
    --- FAIL: TestCapacityScheduling/cross-namespace_preemption_with_three_elasticquota (10.40s)
```

**Comment by Huang-Wei** [comment]
@zwpaper ^^ FYI

**Comment by Huang-Wei** [comment]
The most likely factor is the new version of controller-runtime, we (have to) bump it to v0.15.0. I will also take a look.

**Comment by Huang-Wei** [comment]
> it keeps report 
>
> ```
> E0804 15:56:02.187916   55780 framework.go:716] "Failed running RemovePod on PreFilter plugin" err="error reading > \"PreFilterInterPodAffinity\" from cycleState: not found" plugin="InterPodAffinity" pod="ns2/t1-p5"
> ```

@zwpaper I also spot this while debugging. I'm pretty sure it's a regression introduced in upstream v1.27. Let me file a fix in k/k.

**Comment by Huang-Wei** [comment]
@zwpaper to unblock bumping master to 1.27, I commented out those preemption tests. We can revert them once the upstream fix is available in the next v1.27 patch release. PTAL.

**Comment by zwpaper** [comment]
wow, I have tried and did not found that changes, let me have a look at the k/k issue and find out is there anything I can help.

/lgtm

**Pull request merged**
