### PR TITLE
Add compatibility matrix for NRT plugin

### PR DESCRIPTION
**Pull request by PiotrProkop**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Add README.md section to NRT plugin describing compatibility between versions of NRT CRD, scheduler-plugins and NFD.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by PiotrProkop** [comment]
@swatisehgal @ffromani please take a look.

**Review by ffromani — COMMENTED** [review]
/lgtm
thanks for writing down this!

**Review by swatisehgal — APPROVED** [review]
/lgtm

Thanks for this PR, it is very much appreciated!

**Comment by swatisehgal** [comment]
/assign @Huang-Wei 
for approval

**Pull request merged**
