### PR TITLE
Doc: update doc to fix minor typo

### PR DESCRIPTION
**Pull request by chloejiwon**
Replace `instal` -> `install`

### CODE REVIEW

**Comment by chloejiwon** [comment]
I signed it

**Review by seanmalloy — APPROVED** [review]

**Comment by seanmalloy** [comment]
Looks like the integration tests are sometimes timing out. To me it feels like this started happening after the bump to k/k 1.20.

/test pull-scheduler-plugins-integration-test-master

**Comment by Huang-Wei** [comment]
> Looks like the integration tests are sometimes timing out. 

Some coscheduling tests intentionally spawn the Pods interleavingly, and hence cost extra cycles to complete the tests. I think this is the part that takes the most time of our integration tests. This issue cannot be fully resolved without upstream framework changes.

> To me it feels like this started happening after the bump to k/k 1.20.

Without changes newly introduced along with 1.20 bumping, the integration test sometimes was already very close to timeout (10m) - #172's integration test spent 9m57s... So with new integration tests introduced, the test runs overtime frequently than before.

**Pull request merged**
