### PR TITLE
Documents update for release v0.28.8

### PR DESCRIPTION
**Pull request by Huang-Wei**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Update document and Helm chart for release 0.28.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
@tenzen-y could you help review?

**Comment by tenzen-y** [comment]
> @tenzen-y could you help review?

ACK

**Review by tenzen-y — COMMENTED** [review]
Thank you!
/lgtm

**Pull request merged**
