### PR TITLE
nrt: api: add manual conversion (prereq for noderesourcetopology using the reserve plugin) [1/3]

### PR DESCRIPTION
**Pull request by fromanirh**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
if we try to run `hack/update-codegen.sh`, for example to add new fields to the NodeTopologyMatchArgs, we get this message:
```
E0915 14:12:39.348208  143048 conversion.go:755] Warning: could not find nor generate a final Conversion function for sigs.k8s.io/scheduler-plugins/apis/config/v1beta2.NodeResourceTopologyMatchArgs -> sigs.k8s.io/scheduler-plugins/apis/config.NodeResourceTopologyMatchArgs
E0915 14:12:39.348248  143048 conversion.go:756]   the following fields need manual conversion:
E0915 14:12:39.348252  143048 conversion.go:758]       - ScoringStrategy
```

After closer inspection, the current conversion code for ScoringStrategy was added to the autogenerated code: https://github.com/kubernetes-sigs/scheduler-plugins/blob/v0.23.10/apis/config/v1beta3/zz_generated.conversion.go#L233

This works, but it's a bit fragile, because attempting to regenerate the conversion will fail - no conversion will be generated, and the manually added code will be lost.

In order to improve, and to avoid changing the existing API, we add manually generated conversion code, which is simple and repetitive enough, and can still leverage some autogenerated helpers.

#### Which issue(s) this PR fixes:
Fixes N/A

#### Special notes for your reviewer:
```
NONE
```

### CODE REVIEW

**Comment by swatisehgal** [comment]
/lgtm
Thanks for the PR!

/assign @Huang-Wei
for approval

**Comment by fromanirh** [comment]
> /lgtm Thanks for the PR!
> 
> /assign @Huang-Wei for approval

can I also get `ok-to-test` please? :)

**Comment by fromanirh** [comment]
superceded by https://github.com/kubernetes-sigs/scheduler-plugins/pull/438

**Pull request closed without merging**
