### PR TITLE
Coscheduling: Remove the postBind filter in the KubeSchedulerConfiguration

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
I removed the PostBind filter in the KubeSchedulerConfiguration because the PostBind filter was removed in the https://github.com/kubernetes-sigs/scheduler-plugins/pull/554.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
I think that it would be better to cherry-pick this to the release-0.26 and release-0.27 branches.

**Comment by Huang-Wei** [comment]
> I think that it would be better to cherry-pick this to the release-0.26 and release-0.27 branches.

Actually specifying a non-existent extension point would fail scheduler's startup. But yes, let's fix the documents. And, we should turn to using `MultiPoint` to simplify the scheduler config.

/lgtm
/approve

**Comment by tenzen-y** [comment]
> > I think that it would be better to cherry-pick this to the release-0.26 and release-0.27 branches.
> 
> Actually specifying a non-existent extension point would fail scheduler's startup. But yes, let's fix the documents. And, we should turn to using `MultiPoint` to simplify the scheduler config.
> 
> /lgtm /approve

That makes sense.

**Pull request merged**
