### PR TITLE
bump deps to k8s 1.19.9

### PR DESCRIPTION
**Pull request by seanmalloy**

### CODE REVIEW

**Comment by seanmalloy** [comment]
I have confirmed that it complies and unit tests pass on my laptop. I'd like to build a scheduler container image and confirm that it works before removing the hold.

/hold

**Comment by seanmalloy** [comment]
I was able to build the scheduler container image and run it in a kind cluster.

/hold cancel

**Comment by seanmalloy** [comment]
I believe we want to make this change to the master branch and then cherry-pick it to the release-1.19 branch. Let me know if this is not how you want me to do it.

/assign @Huang-Wei 
/cc @denkensk

**Comment by seanmalloy** [comment]
I believe we want to make this change to the master branch and then cherry-pick it to the release-1.19 branch. Let me know if this is not how you want it done.

/assign @Huang-Wei 
/cc @denkensk

**Comment by Huang-Wei** [comment]
/hold

Let's wait for #143 to be merged.

**Pull request merged**
