### PR TITLE
Documents update for release v0.26.7

### PR DESCRIPTION
**Pull request by Huang-Wei**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Update document and Helm chart for release 0.26.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

- [ ] TODO: cherrypick this to `release-1.26` once merged

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
/unhold

/assign @zwpaper
Could you take a look?

**Comment by zwpaper** [comment]
/lgtm 

Also, there is one more thing I would like to mention, how about we add a helm chart asset in the release? As the release page would always be one of the first beginnings when users come to us, they could easily start with downloading the Chart.

**Comment by Huang-Wei** [comment]
> how about we add a helm chart asset in the release?

I'm thinking of hosting the helm artifacts using github pages. Please open an issue to track it. For now, users have to install from the sub-directory (`manifests/install/charts/as-a-second-scheduler/templates/configmap.yaml`) which is not good UX.

**Comment by zwpaper** [comment]
> I'm thinking of hosting the helm artifacts using github pages.

I mistakenly remembered that we could not create a project GitHub page, the GitHub page would definitely be a better place for hosting the chart.

https://github.com/kubernetes-sigs/scheduler-plugins/issues/607 created an issue and we can discuss it there.

**Pull request merged**
