### PR TITLE
cleanup: remove ioutil for new go version

### PR DESCRIPTION
**Pull request by my-git9**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The io/ioutil package has been deprated in go 1.16: https://go.dev/doc/go1.16#ioutil
Mybe we should remove it.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
/lgtm
/approve

Thanks @my-git9

**Comment by my-git9** [comment]
> /lgtm /approve
> 
> Thanks @my-git9

Hi, @Huang-Wei I want to apply to be a member of kubernetes-sigs, can you sponsor me?

**Comment by my-git9** [comment]
> > Hi, @Huang-Wei I want to apply to be a member of kubernetes-sigs, can you sponsor me?
> 
> Sure, just follow the GH template to apply for k8s member, and tag me in that issue.

Thanks a lot!

**Pull request merged**
