### PR TITLE
Documents update for release v0.25.7

### PR DESCRIPTION
**Pull request by Huang-Wei**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Update document and Helm chart for release 0.25.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
> /hold for [kubernetes/k8s.io#4890](https://github.com/kubernetes/k8s.io/pull/4890) to be merged first.

Need to wait for a while for the image to be live:

```
$ docker pull registry.k8s.io/scheduler-plugins/kube-scheduler:v0.25.7
Error response from daemon: manifest for registry.k8s.io/scheduler-plugins/kube-scheduler:v0.25.7 not found: manifest unknown: Failed to fetch "v0.25.7"
```

**Comment by zwpaper** [comment]
I have checked just now, and all 4 images, kube-scheduler, and controller in amd64 and arm64 are pullable now

**Comment by Huang-Wei** [comment]
> I have checked just now, and all 4 images, kube-scheduler, and controller in amd64 and arm64 are pullable now

Great. Could you /lgtm?

/unhold

**Pull request merged**
