### PR TITLE
Documents update for release v0.27.8

### PR DESCRIPTION
**Pull request by Huang-Wei**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Update document and Helm chart for release 0.27.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

TODOs:

- [ ] cherrypick this to release-1.27 once merged in master

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
@Huang-Wei Can we cherry-pick this into the release-1.27 branch once this is merged into the main branch?

**Comment by Huang-Wei** [comment]
Yes, it's marked as a todo in the description section.

**Comment by tenzen-y** [comment]
> Yes, it's marked as a todo in the description section.

Oops, I missed the description. Thanks!

**Pull request merged**
