### PR TITLE
Cherry pick: Upgrade the controller image version of the all-in-one.yaml

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Cherry-pick of #555 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Upgrade the controller image version of the all-in-one.yaml.
```

### CODE REVIEW

**Comment by ffromani** [comment]
Asking because I'm not too familiar yet with the project standards: do we usually do cherry-picks?

**Comment by tenzen-y** [comment]
> Asking because I'm not too familiar yet with the project standards: do we usually do cherry-picks?

IIUC, this repo follows the kubernetes cherry-pick [policy](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md).

I think we should push this commit to the release-1.25 branch, as the all-in-one manifest doesn't work. Since specifying an incorrect controller image.

**Comment by tenzen-y** [comment]
cc: @Huang-Wei @denkensk

**Comment by ffromani** [comment]
/approve
/hold

Thanks @tenzen-y !
I think in this case the cherry-pick is warranted, but I'd like @Huang-Wei / @denkensk to chime in and add their input

**Comment by ffromani** [comment]
/hold cancel
I don't have approver rights here so not needed :)

**Review by Huang-Wei — COMMENTED** [review]
/lgtm
/approve

Sry i always forgot to update all-in-one.yaml...

**Pull request merged**
