### PR TITLE
Fix PodGroup CRD definition has no status field schema

### PR DESCRIPTION
**Pull request by penglei**

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
I would think this CRD should be generated from https://github.com/kubernetes-sigs/scheduler-plugins/blob/79882332af9f2635236c8992a439711b4a0cf279/pkg/apis/scheduling/v1alpha1/types.go#L116. Maybe this PR could add those generators + verify scripts to check them too?

**Comment by Huang-Wei** [comment]
> Maybe this PR could add those generators + verify scripts to check them too?

Sounds like a great idea.

@penglei would you like to extend this PR to introduce an automatic script to verify/generatee the missing pieces in the CRD definition yaml?

**Comment by penglei** [comment]
> > Maybe this PR could add those generators + verify scripts to check them too?
> 
> Sounds like a great idea.
> 
> @penglei would you like to extend this PR to introduce an automatic script to verify/generatee the missing pieces in the CRD definition yaml?

Yes, that's a great idea, I'll do the follow up.

I'm not familiar with related technical solutions. Do you have any suggestions on how to verify the missing pieces? (I think we can do a comparison between the newly generated yaml file and the old existence.)

**Comment by Huang-Wei** [comment]
@penglei I guess some tools can be leveraged, e.g., https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/controller-gen.

A generic approach should be like this:

1. Use a tool to generate a CRD.yaml (e.g., `controller-gen crd <args>`)
2. Diff the CRD.yaml with the in-place yaml (e.g., `diff <output of 1> manifests/coscheduling/crd.yaml`)
3. Return the return code of above `diff` command, also output the diff is they're different.

It's very high-level, some logic may be adjusted. Or, even some repo may already have this verification script.

**Comment by Huang-Wei** [comment]
But I think we can do that in a follow-up PR. @damemi @denkensk WDYT?

**Comment by cwdsuzhou** [comment]
Agree with @Huang-Wei , do this in another PR may be better

**Comment by denkensk** [comment]
+1 
It's common requirements for all CRDs. We can do it in another pr.
And In this PR, Manually add missing fields is ok. @Huang-Wei @damemi

**Comment by damemi** [comment]
Yeah, another PR is fine by me :) Just wanted to suggest that we should make sure these are generated/verified. I agree with @Huang-Wei's approach with [controller-gen](https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/controller-gen)

**Comment by Huang-Wei** [comment]
/lgtm
/approve

Created a follow-up issue #151.

**Pull request merged**
